@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJkdW1teSIsImVtYWlsIjoiZHVtbXlAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTMxODE1MjQsImV4cCI6MTc1MzI2NzkyNH0.U5rL4UR8bPHxZAqDyW30DPsYcnsUe0a4bPM2L9hz0Kc

### Register pengguna baru
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "johndoe",
  "email": "johndoe@example.com",
  "password": "password123"
}

### Login untuk mendapatkan token
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "johndoe@example.com",
  "password": "password123"
}