@baseUrl = http://localhost:3000
@token = 

### Register pengguna baru
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "dummy",
  "email": "dummy@example.com",
  "password": "password123"
}

### Login untuk mendapatkan token
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}