@baseUrl = http://localhost:3000
@baseUrl = http://localhost:3000

### --- Token User: ADMIN ---
@token_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoiYWRtaW51c2VyIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUzNzgyNTAyLCJleHAiOjE3NTM4Njg5MDJ9.cmFwhq2QAf1S3NKcHxPHB0m9Z4tK8iDXvTurgpwNACQ

### --- Token User: SALES (ID: 2) ---
@token_sales = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJzYWxlc0BleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoic2FsZXN1c2VyIiwicm9sZSI6IlNBTEVTIiwiaWF0IjoxNzUzNzgyNTM5LCJleHAiOjE3NTM4Njg5Mzl9.x8zMzqNmkUiQb2ljGqZYyvwRtI9fNF2PVV6OKGFI2Og
@token_sales2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJzYWxlczJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6InNhbGVzMnVzZXIiLCJyb2xlIjoiU0FMRVMiLCJpYXQiOjE3NTM3ODI1NjcsImV4cCI6MTc1Mzg2ODk2N30.aP2uRbxrSwtX7dehCUzIhgg1mT9Acm5kflvNQF5ouLs

### --- Token User: MANAGER (ID: 3) ---
@token_manager = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJtYW5hZ2VyQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJtYW5hZ2VydXNlciIsInJvbGUiOiJNQU5BR0VSIiwiaWF0IjoxNzUzNzgyNjAxLCJleHAiOjE3NTM4NjkwMDF9.CZ1Xhq3Oxp1ahnHuMcGlfubLJemuTS5QFkclRmDQjho

### --- Token User: VIEWER (ID: 4) ---
@token_viewer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ2aWV3ZXJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6InZpZXdlcnVzZXIiLCJyb2xlIjoiVklFV0VSIiwiaWF0IjoxNzUzNzgyNjMwLCJleHAiOjE3NTM4NjkwMzB9.qy-GSJ1gz5FS2xoxctWvEh78EmIqJ45iFcnvzKPDo40

### Login untuk mendapatkan token
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "salesuser",
  "password": "password123"
}

### Membuat pelanggan baru
POST {{baseUrl}}/api/customers
Content-Type: application/json
Authorization: Bearer {{token_sales}}

{
  "name": "Customer by Sales",
  "email": "sales.customer@example.com",
  "phone": "0800000000",
  "address": "Jl. Contoh",
  "company": "Sales Corp"
}

### Mendapatkan semua pelanggan
GET {{baseUrl}}/api/customers
Authorization: Bearer {{token_viewer}}

### Mendapatkan pelanggan berdasarkan ID
GET {{baseUrl}}/api/customers/2
Authorization: Bearer {{token_manager}}

### Memperbarui pelanggan
PATCH {{baseUrl}}/api/customers/2
Content-Type: application/json
Authorization: Bearer {{token_sales}}

{
  "name": "John Smith",
  "phone": "0987654321"
}

### Menghapus pelanggan
DELETE {{baseUrl}}/api/customers/2
Authorization: Bearer {{token_admin}}