@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoiYWRtaW51c2VyIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUzNzcxMjYzLCJleHAiOjE3NTM4NTc2NjN9.2O0rg4y6E1Uow1DcsT7m9Db0mNWRZ-GnlTSa6BoGk-A

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "adminuser",
  "password": "password123"
}

### Get all users
GET {{baseUrl}}/api/users
Authorization: Bearer {{token}}

### Get user by ID
GET {{baseUrl}}/api/users/2
Authorization: Bearer {{token}}

### Create user 
POST {{baseUrl}}/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username" : "yummyuser",
  "email" : "yummy@example.com",
  "password" : "password123"
}

### Update user
PATCH  {{baseUrl}}/api/users/7
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "role": "VIEWER"
}

### Delete user
DELETE {{baseUrl}}/api/users/6
Authorization: Bearer {{token}}