@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOiJqb2huZG9lIiwicm9sZSI6IlZJRVdFUiIsImlhdCI6MTc1Mzc2NjcyMywiZXhwIjoxNzUzODUzMTIzfQ.CZkpv3NCh5oBFeiHhQzhb-ia77c4_VkwF3C2vJwmWeM

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "emailOrUsername": "adminuser",
  "password": "password123"
}

### Get all users
GET {{baseUrl}}/api/users
Authorization: Bearer {{token}}

### Get user by ID
GET {{baseUrl}}/api/users/4
Authorization: Bearer {{token}}

### Create user 
POST {{baseUrl}}/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username" : "yummyuser",
  "email" : "yummy@example.com",
  "password" : "password123"
}

### Update user
PATCH  {{baseUrl}}/api/users/7
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "role": "VIEWER"
}

### Delete user
DELETE {{baseUrl}}/api/users/6
Authorization: Bearer {{token}}